### ISSUE TITLE
browser version needed

### ISSUE THREAD

**Issue by mccoysc** [njl07/otp.js#2]
version Using in IE,chrome,etc, is being needed

**Comment by njl07** [comment]
Hello,

What do you mean ?

**Comment by mccoysc** [comment]
I need a version which can be used in IE,Chrome and so on.

**Comment by njl07** [comment]
This library is for `node` and no browser. If you want to use it inside your browser, you need to have a system that accept `require` modules.

May be use `SystemJS` to load it.

But, I'll rewrite this library in `Typescript` with `browserify` version.
